In [1]:
import numpy as np

# Question 1

In [2]:
x = np.random.randint(5,90,10)
#x = x.astype(int)
print("x: ",x)

y = np.random.randint(5,95,10)
#y = y.astype(int)
print("y: ",y)

np.array_equal(x,y)

x:  [22 17 35 43 76 37 45 38 81 11]
y:  [31 70 46 60 58 83 16 18 10 84]


False

# Question 2

In [4]:
ar = np.zeros((8))
ar

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
ar[4]=1
ar

array([0., 0., 0., 0., 1., 0., 0., 0.])

In [6]:
ar.flags.writeable= False

In [7]:
ar[5]=1

ValueError: assignment destination is read-only

# Question 3

In [11]:
y = np.random.randint(1,43,10)
#y = y.astype(int)
print("Original array:")
print(y)

y[y.argmax()] = 100
print("Maximum value replaced by 100:")
print(y)

y[y.argmin()] = 0
print("Minimum value replaced by 0:")
print(y)

Original array:
[37 24 19  9 11 17 21 19 24 36]
Maximum value replaced by 100:
[100  24  19   9  11  17  21  19  24  36]
Minimum value replaced by 0:
[100  24  19   0  11  17  21  19  24  36]


# Question 4

In [12]:
arr = np.array([15,24,98,65,43,20,78,83])
print("Array is: ", arr)

n = int(input("Enter the value to which nearest element is to be found: "))

diff_arr = np.absolute(arr-n)
#diff_arr

index = diff_arr.argmin()
#index

print("Nearest element to the given values is : ", arr[index])

Array is:  [15 24 98 65 43 20 78 83]
Enter the value to which nearest element is to be found: 59
Nearest element to the given values is :  65


# Question 5

In [13]:
arr = np.random.rand(4,5)
print("Matrix is:\n", arr)

arr2 = arr - arr.mean(axis=1, keepdims=True)
print("\nAfter Subtracting the mean of each row:\n", arr2)

Matrix is:
 [[0.43190157 0.36251547 0.60384391 0.25078078 0.68503214]
 [0.76598351 0.60303004 0.49067432 0.07910846 0.54193901]
 [0.44208062 0.35220465 0.44256671 0.826057   0.55053465]
 [0.34703698 0.48581777 0.0737352  0.18976848 0.0398603 ]]

After Subtracting the mean of each row:
 [[-0.03491321 -0.1042993   0.13702913 -0.21603399  0.21821737]
 [ 0.26983644  0.10688297 -0.00547275 -0.41703861  0.04579194]
 [-0.08060811 -0.17048407 -0.08012202  0.30336828  0.02784593]
 [ 0.11979323  0.25857403 -0.15350855 -0.03747527 -0.18738344]]


In [14]:
import pandas as pd

# Question 6

In [15]:
x = pd.Series([1,4,3,8,6,9])
print("Series Before Converting index into Columns:")
print(x)
x=x.reset_index()
print("\nDataFrame After Converting index into Columns:")
print(x)

Series Before Converting index into Columns:
0    1
1    4
2    3
3    8
4    6
5    9
dtype: int64

DataFrame After Converting index into Columns:
   index  0
0      0  1
1      1  4
2      2  3
3      3  8
4      4  6
5      5  9


# Question 7

In [17]:
x = pd.Series([1,4,3,8,6,9])
y = pd.Series([2,1,3,5,8,3])

result = x[~x.isin(y)]
print("Items of series X not present in series Y\n",result)

Items of series X not present in series Y
 1    4
4    6
5    9
dtype: int64


# Question 8

In [18]:
x = pd.Series([1,4,3,8,6,9])
# x.describe()
print("Minimum Value is= ",x.min())
print("25%= ",x.quantile(0.25))
print("Median= ",x.median())
print("75%= ",x.quantile(0.75))
print("Mean= ",x.mean())
print("Maximum Value is= ",x.max())

Minimum Value is=  1
25%=  3.25
Median=  5.0
75%=  7.5
Mean=  5.166666666666667
Maximum Value is=  9


# Question 9

In [19]:
# W3
import pandas as pd
import numpy as np
np.random.RandomState(10)
num_series = pd.Series(np.random.randint(1, 5, [9]))
print("Original Series:")
print(num_series)
print("Top 2 Freq:", num_series.value_counts())
result = num_series[~num_series.isin(num_series.value_counts().index[:1])] = 'Other'
print(num_series)

Original Series:
0    1
1    1
2    1
3    1
4    4
5    1
6    1
7    3
8    4
dtype: int32
Top 2 Freq: 1    6
4    2
3    1
dtype: int64
0        1
1        1
2        1
3        1
4    Other
5        1
6        1
7    Other
8    Other
dtype: object


# Question 10

In [20]:
name = pd.Series(['azam','arbaaz','armaan','rehan','saddam'])
print("Before Capitalizing\n",name)

str_res = name.str.capitalize()
#str_res = str.map(lambda x:x[0].upper)
print("\nAfter Capitalzing first word of each element:\n",str_res)

Before Capitalizing
 0      azam
1    arbaaz
2    armaan
3     rehan
4    saddam
dtype: object

After Capitalzing first word of each element:
 0      Azam
1    Arbaaz
2    Armaan
3     Rehan
4    Saddam
dtype: object
